### ISSUE TITLE
doi for the collection of repos under the research-software-directory organization

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#1]
I'm trying to figure out a good way of assigning a sensible doi to the RSD given that it is divided over a couple of repos.

Maybe the following could be a solution:

1. Make releases only of the landing-page repo. That way, you'll get the most meaningful README (I hope).
2. Adapt landing-page repo to use git submodules (I know, a painful solution, but an accurate one with respect to versions)
3. Add instructions on how to git clone the landing-page repo given that it has submodules because I, for one, will definitely forget
4. Add instruction on how to upgrade landing-page to the latest set of dependency versions
5. move the gh-pages content to ``master/docs`` (is currently just ``master``)

I'd be interested in you opinions @jmaassen @Tommos0

**Comment by Tommos0** [comment]
I agree on creating a DOI for the landing page. However I'm not so worried about the versioning, a single DOI can be good enough.
If we really want DOIs per RSD version, perhaps we can just add the current git commit hash or version tag per repository in a file in landing-page so the references to the exact versions are still there. Basically, I'm not a big fan of using git submodules for this purpose.

**Comment by jspaaks** [comment]
I'm not sure how the pros and cons weigh up, but let's see how it is in practice. Here's why I think this is the best (although perhaps not a good) way:

1. we agree we need a DOI for the RSD
1. if you have a DOI, sites like Zenodo need to be able to provide a ZIP with an exact copy of what that DOI contains.
1. The only reliable way to do so is through submodules

**Comment by jspaaks** [comment]
All done, let's see how it works out in practice.

**Comment by jspaaks** [comment]
This may be relevant if we ever decide to change what we put in a release on Zenodo (FYI whatever is in a submodule does not make it to Zenodo) 

Here's how you can get a snapshot over multiple repositories (you do not need the ``mkdir``s if you're using submodules)

```bash
mkdir research-software-directory && cd research-software-directory

curl -L http://api.github.com/repos/research-software-directory/research-software-directory/tarball/cf62a8c3ebe322dc486c75d487de16a9db3142e8 | tar xzC . --strip 1

mkdir auth-github
curl -L http://api.github.com/repos/research-software-directory/auth-github/tarball/fa3e0e62033dba864437af8c3b929e639428a4ac | tar xzC auth-github --strip 1

mkdir admin
curl -L http://api.github.com/repos/research-software-directory/admin/tarball/6856e70204eac7e0bb5b63cd0c391b13917966d9 | tar xzC admin --strip 1

mkdir backend
curl -L http://api.github.com/repos/research-software-directory/backend/tarball/97c26c5f2825396f03fd029c32c3e21404c3b3a5 | tar xzC backend --strip 1

mkdir db-dump
curl -L http://api.github.com/repos/research-software-directory/db-dump/tarball/f553e6d076471eab390b44d39c915e48f3b27ba4 | tar xzC db-dump --strip 1

mkdir frontend
curl -L http://api.github.com/repos/research-software-directory/frontend/tarball/1d82f242c3b2d15973b50f9a4096a16e72bcb0be | tar xzC frontend --strip 1

mkdir readthedocs
curl -L http://api.github.com/repos/research-software-directory/readthedocs/tarball/362da73a4d594972318d5d11e3d6fb81402a46da | tar xzC readthedocs --strip 1

mkdir tasks-nlesc
curl -L http://api.github.com/repos/research-software-directory/tasks-nlesc/tarball/b4a99564651a547488c3a00efbb0b0ccbd75a7fe | tar xzC tasks-nlesc --strip 1

```
