### ISSUE TITLE
What are proper intervals for each task?

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/landing-page#106]
In production the following tasks should be scheduled:

1. github commits, every day
2. citation data, every day
3. software cache, every 5 minutes
4. zotero / mentions, every day
5. projects, every day
6. nginx cache invalidation, every 5 minutes

The Dockerfile should have the cron or similar daemon as it's command. The repo should have a default schedule configuration file.

@jspaaks , @Tommos0 are the intervals I propose OK?

**Comment by jspaaks** [comment]
1,2 fine; 3 not sure seems a bit much maybe

**Comment by jspaaks** [comment]
Keep in mind the balance of CPU credits should not exceed 20% for t2_small
