### ISSUE TITLE
Download citation files for QTL TableMiner++ does not work

### ISSUE THREAD

**Issue by arnikz** [research-software-directory/landing-page#113]
https://www.research-software.nl/software/qtl-tableminer
I've tried all (i.e. BibTeX, RIS and EndNote) styles but no success.

**Comment by Tommos0** [comment]
This is still on the v1 site. Things have changed for v2:
https://test.research-software.nl/software/qtl-tableminer?1

In this case the citation files still can't be downloaded. I can see you added a CITATION.cff file, but as it is not yet included in any release, downloading citation files won't work until you do so.

**Comment by jspaaks** [comment]
what Tom says. Also, https://github.com/candYgene/QTM/pull/1

**Comment by arnikz** [comment]
Thanks! After merging PR the issue is solved.
