### ISSUE TITLE
Mark for deletion

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/landing-page#114]
Some software items have not been filled in any way. They should be removed and re-added when needed later.

**Comment by sverhoeven** [comment]
* 3d-e-chem-vagrant-box
* kripo-db-web-service
* a-new-generation-of-point-cloud-data-management-systems (paper not software)

**Comment by sverhoeven** [comment]
* aminergic-gpcr-mutation-data-set (dataset not software)

**Comment by sverhoeven** [comment]
Andi should be one software item not 3:
* andi-frontend
* andi-ocpu
* andi-webservices

All three of them have minimal info.

**Comment by sverhoeven** [comment]
* autosubmit (missing doi and any urls, short statement=`Versatile tool to manage Weather and Climate Experiments in diverse Supercomputing Environments`

**Comment by sverhoeven** [comment]
* biographynet-demonstrator (only github filled as https://github.com/BiographyNet/demonstrator )

**Comment by sverhoeven** [comment]
* breed4food-rdf-graphs-pig

**Comment by sverhoeven** [comment]
* casacore (are we contributing to it?)

**Comment by sverhoeven** [comment]
* cdo

**Comment by jspaaks** [comment]
I didn't record the reasons but here's the list:

- https://test.research-software.nl/admin/software/wrfpy
- https://test.research-software.nl/admin/software/wrf-configuration
- https://test.research-software.nl/admin/software/weerbelevings-app
- https://test.research-software.nl/admin/software/vogel-het-uit-ios-app
- https://test.research-software.nl/admin/software/vogel-het-uit-android-app
- https://test.research-software.nl/admin/software/swish-notebook-tomato
- https://test.research-software.nl/admin/software/summer-in-the-city-heatwave-map
- https://test.research-software.nl/admin/software/storyteller-with-querybuilder
- https://test.research-software.nl/admin/software/storyteller-for-embodiedemotions
- https://test.research-software.nl/admin/software/storyteller-for-biographyned
- https://test.research-software.nl/admin/software/spiraljs
- https://test.research-software.nl/admin/software/aa-alert-snr
- https://test.research-software.nl/admin/software/sherlock-dive
- https://test.research-software.nl/admin/software/root
- https://test.research-software.nl/admin/software/roofit
- https://test.research-software.nl/admin/software/qmflows-namd
- https://test.research-software.nl/admin/software/pyroot
- https://test.research-software.nl/admin/software/pycrtools
- https://test.research-software.nl/admin/software/punchcardjs
- https://test.research-software.nl/admin/software/prnu-gpu-desktop
- https://test.research-software.nl/admin/software/picas
- https://test.research-software.nl/admin/software/pdal
- https://test.research-software.nl/admin/software/paxer
- https://test.research-software.nl/admin/software/topic-coherence-for-dutch
- https://test.research-software.nl/admin/software/oxfrei-dataset
- https://test.research-software.nl/admin/software/openifs
- https://test.research-software.nl/admin/software/openearth
- https://test.research-software.nl/admin/software/openda
- https://test.research-software.nl/admin/software/newsreader-hbase
- https://test.research-software.nl/admin/software/micmac
- https://test.research-software.nl/admin/software/metrochartjs
- https://test.research-software.nl/admin/software/mcatnlo
- https://test.research-software.nl/admin/software/matrix-of-scatter
- https://test.research-software.nl/admin/software/matifus
- https://test.research-software.nl/admin/software/linked-data-platform-for-structural-variants-in-human-cancer-genomes
- https://test.research-software.nl/admin/software/liblas
- https://test.research-software.nl/admin/software/kripo-db-web-service
- https://test.research-software.nl/admin/software/knime-plugin-distance-bitvector-modified-tanimoto
- https://test.research-software.nl/admin/software/km3net-real-time-detection-of-neutrinos-using-gpus
- https://test.research-software.nl/admin/software/aa-alert-integration
- https://test.research-software.nl/admin/software/heem-dataset
- https://test.research-software.nl/admin/software/historic-embodied-emotions-model-heem-dataset
- https://test.research-software.nl/admin/software/harmony
- https://test.research-software.nl/admin/software/gpu-kernels-for-gausstransform
- https://test.research-software.nl/admin/software/gpu-kernels-bhattacharya-distance-two-point-sets
- https://test.research-software.nl/admin/software/gaudi
- https://test.research-software.nl/admin/software/embodied-emotions-multi-label-dataset
- https://test.research-software.nl/admin/software/ece2cmor
- https://test.research-software.nl/admin/software/ec-earth
- https://test.research-software.nl/admin/software/dockerized-virtuoso-universal-server
- https://test.research-software.nl/admin/software/dive-plus-queries
- https://test.research-software.nl/admin/software/differential-evolution
- https://test.research-software.nl/admin/software/deltashell
- https://test.research-software.nl/admin/software/delft3d
- https://test.research-software.nl/admin/software/datavaults
- https://test.research-software.nl/admin/software/dalesview
- https://test.research-software.nl/admin/software/cr-tools
- https://test.research-software.nl/admin/software/complearn
- https://test.research-software.nl/admin/software/collatex
- https://test.research-software.nl/admin/software/clustit
- https://test.research-software.nl/admin/software/chemokine-gpcr-mutation-data-set
- https://test.research-software.nl/admin/software/chemical-analytics-platform-vagrant-box

**Comment by jspaaks** [comment]
recap of Stefan's items:

- https://test.research-software.nl/admin/software/3d-e-chem-vagrant-box
- https://test.research-software.nl/admin/software/kripo-db-web-service
- https://test.research-software.nl/admin/software/a-new-generation-of-point-cloud-data-management-systems
- https://test.research-software.nl/admin/software/aminergic-gpcr-mutation-data-set
- https://test.research-software.nl/admin/software/andi-frontend
- https://test.research-software.nl/admin/software/andi-ocpu
- https://test.research-software.nl/admin/software/andi-webservices
- https://test.research-software.nl/admin/software/archimate
- https://test.research-software.nl/admin/software/autosubmit
- https://test.research-software.nl/admin/software/biographynet-demonstrator
- https://test.research-software.nl/admin/software/biographynet-language-analysis-pipeline
- https://test.research-software.nl/admin/software/breed4food-rdf-graphs-pig
- https://test.research-software.nl/admin/software/casacore
- https://test.research-software.nl/admin/software/cdo

**Comment by jspaaks** [comment]
All done now. Closing.
