### ISSUE TITLE
Error when deleting software item 

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#116]
Error when deleting software item 
https://test.research-software.nl/admin/software/matrix-of-scatter
I get
```
mongo:27017: [Errno -2] Name does not resolve
```
Subsequently trying to delete other items does not seem to work (or maybe there's just no feedback)

**Comment by jspaaks** [comment]
Might just be due to the server being offline. Will retry in a little bit

**Comment by Tommos0** [comment]
Yes that was the problem, should work now (I deleted this one)
