### ISSUE TITLE
what is the purpose of the issues link on product pages

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#12]
Currently the software product pages contain a link to issues "For bug reports and issues, please use the Github Issues feature. And don’t forget to check the documentation!" 

https://github.com/research-software-directory/frontend/blob/520d481efe1a454bd3ed76d5cfefacc3aee6f376/templates/software_template.html#L453-L455

The link is incorrect for boatswain and the research software directory but not Xenon.

Can we do without this link here?

**Comment by Tommos0** [comment]
Link has been removed
