### ISSUE TITLE
remove delays/hidden/manual steps while filling in data

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#13]
When I fill in new data in admin.research-software.nl, the process by which I get to see the new data at research-software.nl is unclear. At the very least we should provide some feedback on what a user needs to do next (if there is any user action required) or some feedback on where you are in the process. Sort of a track and trace for your newly entered data if you will.

Ideally, this should all be automated.

Not sure what are the necessary steps for this, maybe @Tommos0 can outline them?

**Comment by Tommos0** [comment]
Server caches all pages for at most 30 minutes, so waiting should work.
An option to circumvent the cache is to add a random parameter to the URL, eg `https://www.research-software.nl/software/boatswain?1`
