### ISSUE TITLE
"in collaboration with"...ourselves

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#2]
if there's no other parties involved with a software tool, it's probably better to leave out the "in collaboration with" block entirely.

**Comment by Tommos0** [comment]
Should we include the eScience Center at all in the list?

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/frontend/commit/e7446c46b4b27f589705f641c98438e81676b62a

**Comment by jspaaks** [comment]
So I made this https://github.com/research-software-directory/backend/pull/3 as a possible solution but maybe ew should instead change the text to "Contributing organizations" as opposed to "In collaboration with".
