### ISSUE TITLE
accumulate plotly graph lines when there are multiple repositories

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#21]
e.g. for the research software directory https://www.research-software.nl/software/research-software-directory, it seems there is little activity because the graph shows only the activity on the landing-page repo, but not the other related repos.

Maybe we could adapt the script such that it accumulates the data for an array of repos? Not sure how that affects how we use the GitHub ID field in de admin interface currently.

**Comment by jspaaks** [comment]
The Plan is as follows:

1. First, I'm gonna try to have the admin interface output a github_id[] with 1 element instead of a github_id of type string.
1. Update the test data based on https://github.com/research-software-directory/landing-page/issues/4 ...*shivers* 
1. Have the frontend code use github_id[0] instead of github_id
1. see if I need to change any tests
1. Then, we also need to go over the production data

Second phase: 
1. Adapt admin interface again such that it outputs [{url: string, commit_stats: bool, citation:bool]},{url:string, commit_stats:bool, citation:bool}, etc]
1. repeat other steps from phase 1

**Comment by jspaaks** [comment]
couple of relevant places

- admin@b5b23d0
   - src/interfaces/resources/software.ts
   - src/components/form/ResourceForm.tsx:30

**Comment by jspaaks** [comment]
I added a key ``githubids`` to all elements in collection ``software`` as follows:
 ```bash
cd stack
# (pull child repos)
docker-compose up --build
docker-compose exec mongo mongo
> use test
> db.software.update( {}, {'$set': {githubids:[]}}, false, true)
```

**Comment by sverhoeven** [comment]
Months without commits should be plotted on yaxes=0, see https://github.com/research-software-directory/frontend/pull/69

**Comment by Tommos0** [comment]
This is done as of https://github.com/research-software-directory/tasks-nlesc/commit/4a5321cbca8bd9ab155b4df330bb7675f2a9c4f5
