### ISSUE TITLE
software.json appears twice (more or less). why?

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#32]
- https://github.com/research-software-directory/backend/blob/99c6beda2893ce369d736cfcc52a9e749d8aa30e/schema/software.json
- https://github.com/research-software-directory/backend/blob/99c6beda2893ce369d736cfcc52a9e749d8aa30e/schema/properties/software.json

**Comment by Tommos0** [comment]
I've split the schema into pure `JSON Schema` definitions (`/schema`), and additional properties (`/schema/properties`), which are not part of the official `JSON schema` definition, but provide some extra metadata for each field.

**Comment by jspaaks** [comment]
can we move the extra properties to the ``admin`` repo, since that's where they are used? In any case, they should not be under ``schema`` (perhaps next to it).

**Comment by sverhoeven** [comment]
The properties now named settings are in the admin repo as https://github.com/research-software-directory/admin/blob/b3f240771eef85d729dc2ac2c67b9c64163a141f/public/settings.json#L1
