### ISSUE TITLE
testimonials not rendered/included

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#33]
e.g. 
```
> db.software.find({"_id": "case-law-app"},{"testimonial": 1})
{ "_id" : "case-law-app", "testimonial" : "It’s quite amazing to see how, thanks to this tool, a student can, in some ways, outperform the expert." }
```
but the site doesn't show it.

**Comment by jspaaks** [comment]
It depends on whether software has corporate projects associate with it.

**Comment by Tommos0** [comment]
Agreed, we have to flatten the structure a little bit into a single schema, merging properties of `corporate_project` and `project`.

**Comment by jspaaks** [comment]
OK, so this issue becomes part of https://github.com/research-software-directory/landing-page/issues/36. Closing this one.
