### ISSUE TITLE
what is the preferred schema notation

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#39]
I noticed we use different schema versions and different ways to point to it:
```bash
$ cd stack
$ grep -nr "[#|$]schema" . 
./admin/mock/schema.json:3:    "$schema": "http://json-schema.org/draft-04/schema#",
./admin/mock/schema.json:139:        "$schema": "http://json-schema.org/draft-04/schema#"
./admin/mock/schema.json:142:    "$schema": "http://json-schema.org/draft-04/schema#",
./admin/mock/schema.json:503:        "$schema": "http://json-schema.org/draft-04/schema#"
./admin/mock/schema.json:872:        "$schema": "http://json-schema.org/draft-04/schema#"
./admin/mock/schema.json:972:        "$schema": "http://json-schema.org/draft2-3/schema#"
./admin/src/interfaces/json-schema.ts:5:  '#schema': 'http://json-property.org/draft-04/property#';
Binary file ./backend/.git/index matches
./backend/schema/project.json:9:  "#schema": "http://json-schema.org/draft-04/schema#",
./backend/schema/organization.json:10:  "#schema": "http://json-schema.org/draft-04/schema#",
./backend/schema/person.json:9:  "#schema": "http://json-schema.org/draft2-3/schema#",
./backend/schema/publication.json:13:  "#schema": "http://json-schema.org/draft-04/schema#",
./backend/schema/software.json:2:    "$schema": "http://json-schema.org/draft-06/schema",
```
Is there a preferred way # v $ and is there a preferred schema version. Choosing one version will decrease chance of hard-to-find bugs in the future

**Comment by Tommos0** [comment]
Ah yes this is a bit messy atm. http://json-schema.org/specification.html says:
> The latest Internet-Drafts at the IETF are the draft-handrews-json-schema*-00 (Core and Validation) and draft-handrews-json-schema*-01 (Hyper-Schema and Relative JSON Pointer) documents, which correspond to the draft-07 meta-schemas. These were published on 2017-11-19 (-00) and 2018-01-19 (-01).

So I say let's use draft-07 `"$schema": "http://json-schema.org/draft-07/schema#".
We should always use `$` and not `#`. Before the schemas were stored in MongoDB, which doesn't allow fields starting with `$` (some Mongo commands start with $), so any `#` is a leftover from a incomplete refactoring.
