### ISSUE TITLE
millis is a str?

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#4]
I just added some items to Zotero, ran the sync http://admin.research-software.nl/zotero_import , refreshed the index, went to my new item ``boatswain``, got an error.

Not sure but could have something to do with [``.createdAt``](https://github.com/research-software-directory/frontend/blob/ceb9e3112ca5e925deeddb85d91dbe4863a305f9/templates/software_template.html#L5) being a ``str`` instead of an ``int``?

**Comment by Tommos0** [comment]
createdAt is set to an empty string, I will fix this
https://admin.research-software.nl/api/software/boatswain
```
{
"createdAt": "",
"updatedAt": 1516207191,
"id": "boatswain",
"schema": "software",
"name": "boatswain",
"githubid": "NLeSC/boatswain",
"citation": "",
"doi": "10.5281/zenodo.1149011",
"tagLine": "",
"shortStatement": "",
"readMore": "",
"statement": "",
"contactPerson": "",
"tags": [],
"highlighted": "",
"published": false,
"contributor": [],
"mainUrl": "",
"license": [],
"usedInProject": [],
"outputOfProject": [],
"contributingOrganization": [],
"programmingLanguage": [],
"zoteroKey": "GAT2QRMY",
"releases": [],
"testimonial": "",
"testimonialBy": "",
"description": "This release only contains some updates for pytests.",
"codeRepository": "https://github.com/NLeSC/boatswain",
"website": "https://github.com/NLeSC/boatswain",
"corporateProjects": [],
"mentions": {},
"relatedSoftware": []
}
```

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/backend/commit/5be4a103eccd0f4695f361a3aca95cbf812f7e2d

**Comment by jspaaks** [comment]
I think the test data still has the old data, I'm getting the same error.
