### ISSUE TITLE
Last update date does not get updated

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/landing-page#40]
Yesterday I pushed few commits for SPOT but the last update date does not change.

**Comment by Tommos0** [comment]
Current implementation shows commits in the `master` branch of a single GitHub repository, in the case of SPOT  this is `NLeSC/spot` (with last commit Dec 4th).
We have an update pending to support multiple GitHub repos (https://github.com/research-software-directory/backend/pull/11 https://github.com/research-software-directory/frontend/pull/69/commits/5e940fb62b765792fac55eb81a071c369a69b9b9).
Optionally we can try to implement multiple branches as well (needs to be supported in the GitHub API).

**Comment by sverhoeven** [comment]
commits are from master branch only. We're currently undecided if we want to also include commits from other branches. Closing for now.
