### ISSUE TITLE
public membership is needed to update the details of the software

### ISSUE THREAD

**Issue by fdiblen** [research-software-directory/landing-page#41]
The user should be a public member of the organization in order to change the details of the listed software. That should be mentioned somewhere.

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/auth-github/commit/d29d7ae8e3185fef4ec9f484c9c7daf15ec0a2f0

**Comment by jspaaks** [comment]
https://help.github.com/articles/publicizing-or-hiding-organization-membership/
