### ISSUE TITLE
Logos broken

### ISSUE THREAD

**Issue by dafnevk** [research-software-directory/landing-page#44]
The logo of UTwente is not correctly shown, e.g. at https://www.research-software.nl/software/nlppln.

**Comment by jspaaks** [comment]
Same for Koninklijke Bibliotheek https://www.research-software.nl/software/ochre

**Comment by sverhoeven** [comment]
Going to switch to base64 encoded blob in database for organization logos and avatar for persons.

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/frontend/commit/ecd9a2b22d11d80b2cb19bacabba9033bd62e6ba
