### ISSUE TITLE
Broken citation downloads

### ISSUE THREAD

**Issue by Tommos0** [research-software-directory/landing-page#45]
According to google crawler, error 400 on:

  | Prioriteit | URL | Reactiecode | Gedetecteerd
-- | -- | -- | -- | --
  | 1 | cite/omuse?format=bibtex | 400 | 26-1-18
  | 2 | cite/3d-e-chem-knime-silicos-it?format=bibtex | 400 | 27-1-18
  | 3 | cite/3d-e-chem-vagrant-box?format=bibtex | 400 | 27-1-18
  | 4 | cite/pidimehs-library?format=bibtex | 400 | 27-1-18
  | 5 | cite/mcfly?format=bibtex | 400 | 26-1-18
  | 6 | cite/boatswain?format=bibtex | 400 | 18-1-18

**Comment by sverhoeven** [comment]
See also https://github.com/research-software-directory/landing-page/issues/85

**Comment by jspaaks** [comment]
1. https://research-software.nl/software/omuse
    - bitbucket repo, wontfix for now
1. https://research-software.nl/software/3d-e-chem-knime-silicos-it
    - wontfix, item will be deleted
1. https://research-software.nl/software/3d-e-chem-vagrant-box
    - wontfix item will be deleted
1. https://research-software.nl/software/pidimehs-library
    - bitbucket repo, wontfix for now
1. https://research-software.nl/software/mcfly
    - fixed (added a CITATION.cff)
1. https://research-software.nl/software/boatswain
    - fixed (added a CITATION.cff)
