### ISSUE TITLE
Clicking next page should move page back to top

### ISSUE THREAD

**Issue by tbkkr** [research-software-directory/landing-page#47]
If you click 2, 3, 4 etc, you keep getting stuck at the bottom of the page. This should auto-scroll to the top of the page I guess.

**Comment by sverhoeven** [comment]
What is the expected behavior from others?

**Comment by Tommos0** [comment]
I don't agree, for me personally it looks better if things stay in the same place

**Comment by tbkkr** [comment]
Hi,

I’m not so sure if that is really common. I think the expected and typical behavior is to move to the top of the page. For example, see
https://www.bol.com/nl/l/monitoren-kantoor/N/10460+4274299033/?page=2
https://www.coolblue.nl/cameras/systeemcameras?pagina=2

Being on page 1, clicking ‘2’ on the bottom and the ending up at the bottom of page 2 is actually inefficient for the visitor. It requires the visitor to scroll back up to see the rest of the entries, and then to scroll back down to go to page 3. Also, given the fact that entries are sorted on Mentions and Last updated, would also make it more reasonable to start at the top of the page.


Van: Tom Klaver <notifications@github.com>
Verzonden: vrijdag 4 mei 2018 10:54
Aan: research-software-directory/landing-page <landing-page@noreply.github.com>
CC: Tom Bakker <t.bakker@esciencecenter.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [research-software-directory/landing-page] Clicking next page should move page back to top (#47)


I don't agree, for me personally it looks better if things stay in the same place

**Comment by jspaaks** [comment]
I agree with @tbkkr scrolling back up is the expected behavior.
