### ISSUE TITLE
Empty pages

### ISSUE THREAD

**Issue by Tommos0** [research-software-directory/landing-page#5]
Some pages are still really empty, they should either be filled or be unpublished. Let's keep a running list here:

- ~~https://example-of-a-fixed-one~~
- ~~https://www.research-software.nl/software/breed4food-rdf-graphs-pig~~
- ~~https://www.research-software.nl/software/research-software-directory~~
- ~~https://www.research-software.nl/software/boatswain~~

**Comment by jspaaks** [comment]
fixed all pages mentioned above by either adding data or unpublishing. Additionally, went over all other software cards to see if they at least provided enough information to fill the index page, and if they did not, I unpublished them.
