### ISSUE TITLE
various time formats in use

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#50]
we store datetime in different ways, e.g.
- as integer seconds since 1970
- as plain string
- as string with format datetime
- github ISO8601 strings

we should make this consistent across the board. I vote to use whatever github commit dates is using (something along the lines of ``2018-02-27T10:57:07Z`` I believe).

We should store all datetimes using 1-second precision; and enforce this format where we can. When information is unknown, e.g. the hour is not specified, let's asume the lowest possible value for that part, e.g. ``2018-01-01T00:00:00Z`` if only the year was specified.

**Comment by sverhoeven** [comment]
Datetimes occur in at least:
* commit task, from GitHub
* citiation/release task, from Zenodo
* zotero task
* mongo updatedAt, createdAt

**Comment by sverhoeven** [comment]
Looks like you want to specify `date` as `format`.
You can have `format` and `pattern` together for the same field. I would use both. 

The `format=date-time` minimizes the month for example to 1-12 while the `pattern` disallows a time component.

**Comment by jspaaks** [comment]
ok, so I guess if we use both that means all our usages of time need to become:
```json
{
   "format": "date-time",
   "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
   "type": "string"
}
```

**Comment by sverhoeven** [comment]
Yep
