### ISSUE TITLE
Remove quotation marks from testimonial and testimonialBy before submit

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#62]
The frontend already applies quotation marks.

**Comment by sverhoeven** [comment]
Add help to admin form element that explains not to add additional quotes

**Comment by jspaaks** [comment]
Add regex pattern to testimonial string https://github.com/research-software-directory/backend/blob/677d919d733b953bffa33c386c1b0fcbd75505ec/schemas/software.json#L582-L585
```json
"pattern": "[a-zA-Z0-9\ !@#$%-_+=;:,.?]+\."
```
(not sure if we should enforce the closing period)
