### ISSUE TITLE
markdown links in shortStatement lead to render weirdness

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#63]
https://www.research-software.nl/software/eecology-sms-reciever has 
this string for its ``shortStatement``: 
```text
If you have birds flying around carrying [UvA-BiTS](http://www.uva-bits.nl/) trackers then this software can save the SMS messages containing the birds last known positions which are send by the tracker into the UvA Bird tracking systems central database.
```

Looks like the markdown link makes the frontend stumble. Probably best to disallow markdown in the ``shortStatement``.

also theres a typo in the title and thus id 
reciever -> receiver

**Comment by sverhoeven** [comment]
Is this fixed in v2?

**Comment by jspaaks** [comment]
AFAIK, this has not been addressed. The error no longer happens, because I changed the data, but maybe we could add a ``pattern`` regex to the shortStatement string https://github.com/research-software-directory/backend/blob/677d919d733b953bffa33c386c1b0fcbd75505ec/schemas/software.json#L538-L541for improved robustness and to avoid ugliness in the shortStatements.

something like: 
`[a-zA-Z0-9,.;:-_]```
