### ISSUE TITLE
add Maastricht University

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#66]
moved from https://github.com/research-software-directory/instruction/issues/63

**Comment by jspaaks** [comment]
in mongo shell do

```javascript
var a = new Timestamp();
db.organizations.insertOne({
   _id:"maastricht-university",
   createdAt: a,
   updatedAt: a,
   schema: "organization",
   description: "",
   logo:"",
   name: "Maastricht University",
   website: "https://www.maastrichtuniversity.nl/"
});
```

**Comment by Tommos0** [comment]
var a =Math.round((new Date().getTime())/1000);
db.organization.insertOne({
   _id:"maastricht-university",
   createdAt: a,
   updatedAt: a,
   schema: "organization",
   description: "",
   logo:"",
   name: "Maastricht University",
   website: "https://www.maastrichtuniversity.nl/"
});
