### ISSUE TITLE
Add image upload functionality to admin interface

### ISSUE THREAD

**Issue by Tommos0** [research-software-directory/landing-page#67]
Add the organization logo and person avatar as base64 encoded string to db.

**Comment by sverhoeven** [comment]
Its already gone

**Comment by sverhoeven** [comment]
We could use something like https://www.npmjs.com/package/react-avatar-editor to storage an image as base64 inside the software record.

**Comment by jspaaks** [comment]
don't forget to delete images that you dont need anymore

**Comment by Tommos0** [comment]
https://github.com/research-software-directory/frontend/commit/ecd9a2b22d11d80b2cb19bacabba9033bd62e6ba
