### ISSUE TITLE
testimonial doesn't show when there is no project

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#68]
e.g. https://www.research-software.nl/software/case-law-app
https://api.research-software.nl/software/case-law-app

**Comment by jspaaks** [comment]
the admin interface write entries to key ``usedInProject``, while the frontend uses ``corporateProjects``.

**Comment by jspaaks** [comment]
Still the case in ceab3b7e1f224f9041ee5909ff97de14377c97ad: the condition is ``corporateProjects`` (which will become ``related.projects`` BTW):

https://github.com/research-software-directory/frontend/blob/ceab3b7e1f224f9041ee5909ff97de14377c97ad/templates/software/projects.html#L1

followed by another condition related to testimonials:

https://github.com/research-software-directory/frontend/blob/ceab3b7e1f224f9041ee5909ff97de14377c97ad/templates/software/projects.html#L9-L14

Once we start using ``related.projects`` case-law-app's problem will like be solved automatically. I don't think we have a case where we have a tool but not an entry on esciencecenter.nl/projects to relate it to.

**Comment by sverhoeven** [comment]
Case law page now renders testimonial section and the project section.

**Comment by jspaaks** [comment]
Good stuff
