### ISSUE TITLE
question regarding best practices CITATION.cff and DOIs

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#77]
Currently, there is an inconsistency in how we use CITATION.cff files and DOIs. The workflow is as follows:

1. For a given repository on GitHub, set up GitHub-Zenodo integration such that making a new release on GitHub triggers assigning a DOI by Zenodo
1. work on code until we're ready to make a new release, commit everything and push to GitHub 
1. push the 'new release' button on GitHub
1. check what DOI was assigned to the release
1. update the CITATION.cff file on GitHub to have it point to the lastest release

There are a couple of problems with this workflow:

1. When resolving a DOI, you'll be directed to the Zenodo page, where 
    1. you will find that the ``doi`` key from the CITATION.cff file describes the previous release (if there is one)
    1. you will find that the ``commit`` key from the CITATION.cff describes a previous commit
    1. you will find that the metadata is likely not the same as what you entered in the CITATION.cff

After some searching, it seems that the codemeta people (e.g. @cboettig) and Zenodo people (e.g. @lhansen) are aware of this problem, see discussion here: https://github.com/codemeta/codemeta/issues/167, https://github.com/codemeta/codemeta/issues/24#issuecomment-164676080

There is a couple of ways in which we can work around this, none of which seem like complete solutions though:

---

**(1/5) doi in CITATION.cff on GitHub should be the concept-doi**

Under this option, you would have the CITATION.cff include a ``doi`` key that points to the ``concept-doi`` / 'cite all versions'-DOI. 

- pros
    1. Easy to implement
    1. No code changes necessary anywhere
    1. the DOI on the frontend will be the concept doi, which could be argued is consistent with the fact that the software pages are versionless because they describe the brand, not a specific version
- cons
    1. the key name is ``doi``, not ``concept-doi`` therefore it is expected that the entered value uniquely identlfies a software including its version/commit SHA. Entering a concept-doi in a key named ``doi`` feels like a square peg in a round hole.
    1. Under this option, the Research Software Directory cannot help you cite a specific version of the software, even if you wanted to
    1. Zenodo discourages the use of concept DOIs, because it hampers reproducibility

---

**(2/5) CITATION.cff in GitHub repo but without version information**

Store the CITATION.cff in the GitHub repository, but don't use the ``commit`` field because you can't commit the updated CITATION.cff without changing the commit SHA. If you would then release the software, that release's commit SHA listed in CITATION.cff will be inconsistent with what GitHub and Zenodo have labeled as the release's commit SHA. For similar reasons, you can also not include a ``doi`` in your CITATION.cff under this option, because it is only assigned _after_ you make the release that should contain the DOI information.

- pros
    1. CITATION.cff information lives next to the actual software, i.e. where people/machines expecte it.
    1. release mechanism using GitHub/Zenodo intergration as outlined above works: releases contain a CITATION.cff file in which the provided information is up to date (or at least it can be if the repo authors are diligent)
- cons
    1. Under this option, the Research Software Directory cannot help you cite a specific version of the software, even if you wanted to

---

**(3/5) CITATION.cff in admin interface, not in repo**

Under this option, the CITATION.cff information is not stored with the software, such that the DOI and commit information can be updated once the release has been made and a DOI has been assigned.

- pros
    1. allows for correct citation of (only) the latest version of the software, including a version-specific DOI
- cons
    1. CITATION.cff information does not live next to the actual software, i.e. where people/machines expect it.
    1. does not allow for citing multiple versions. 
    1. Information in the Admin's CITATION.cff will likely be out of date when people make a new release on GitHub and forget to update the CITATION.cff information in the Admin interface.

---

**(4/5) conceptdoi field in admin interface, CITATION.cff on GitHub but without version information**

Have a new field ``conceptdoi`` or something in the admin interface, that contains the concept DOI of a software package (sidenote: we should check that the provided DOI is in fact a concept DOI). Then,
- Use Zenodo's API to retrieve all versions, e.g. ``https://zenodo.org/api/records?q=conceptdoi:"10.5281/zenodo.597993"&all_versions=true``. For each version, 
    - visit GitHub, retrieve the CITATION.cff if there is one, generate the Bibtex and other formats ignoring any version information that is found in the CITATION.cff (``doi``, ``version``, and ``commit`` keys).
    - also query the Zenodo API and retrieve the version specific DOI, version, and commit information. 
- Merge the information

The 'Cite this software' section should then only contain the dropdown ``version`` (GitHub tags/releases), the dropdown ``format`` ([BibTeX, RIS, EndNote], and a ``Download`` button). I don't see a use case for offering the DOI directly, only contained within the BibTeX, RIS, EndNote, whathaveyou.
 - pros
    1. allows for citing the correct version of software, including a version-specific DOI
- cons
    1. Requires quite a lot of code changes
    1. Possibly duplicate && inconsistent information in CITATION.cff files when people include the version, commit, or DOI keys (we could check against that, but by then it will be too late--the release has been made at that point)
    1. multi-step workflow to acquire the necessary information (obscures the flow of information)
    1. The metadata that you get after resolving the DOI is usually not the same as what you get from the CITATION.cff (although you have some control over it by placing a ``.zenodo.json`` in the root of your repo).

---

**(5/5) Use manual upload on Zenodo, combined with its 'reserve a DOI' capability**

...

- pros
    1. Full control of the meta information presented alongside a given release on Zenodo 
    1. Under this option, the DOI found in the CITATION.cff can be consistent with the release DOI because you can reserve a DOI
- cons
    1. Unlikely that people will keep this information up to date, there are a lot of things to fill in
    1. The commit key when included in the CITATION.cff, will still be out of date with the release.

**Comment by sverhoeven** [comment]
Replace citationCff with conceptDoi field, used for fetching release doi + cff (which gets stored in own collection by task)
Replace githubUrls with list of just urls, only used for fetching commmits.
