### ISSUE TITLE
Investigate whether using a .zenodo.json file helps with having the correct metadata on Zenodo

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#78]
Including a .zenodo.json file presumably affects the metadata on Zenodo. Might be a way to help solve inconsistencies between the metadata you get after resolving a DOI to the associated landing page on Zenodo and the CITATION.cff data we include in a release.

example
- https://github.com/lnielsen/decouple/blob/master/.zenodo.json (author is a Zenodo developer)
- https://github.com/rocker-org/rocker-versioned/blob/master/.zenodo.json (author is also involved in ~CITATION.cff~ codemeta)
- https://github.com/nipy/nipype/blob/master/.zenodo.json (random example I found on the internets)

Note: the crosswalk table over at codemeta also includes a Zenodo column: https://github.com/codemeta/codemeta/blob/master/crosswalk.csv. I'm not sure if including a .zenodo.json has been superseded by including a ``.codemeta.json`` (can't tell from https://gitter.im/zenodo/zenodo/archives/2016/04/21). A related question was raised on CodeMeta's gitter https://gitter.im/codemeta/codemeta?at=5a1436c3e606d60e34ef896c, but has gone unanswered so far.

@cboettig's response on a blog post by @danielskatz suggests that codemeta will become the standard: https://danielskatzblog.wordpress.com/2017/09/25/software-heritage-and-repository-metadata-a-software-citation-solution#comment-464

**Comment by jspaaks** [comment]
To answer the original question: it does! https://dx.doi.org/10.5281/zenodo.1197183

**Comment by sverhoeven** [comment]
The .zenodo.json is loaded with https://github.com/inveniosoftware/invenio-github/blob/master/invenio_github/utils.py#L52-L66 method. The data of .zenodo.json (extra_metadata) is updated on the defaults and github committers are added as creators last in https://github.com/zenodo/zenodo/blob/master/zenodo/modules/github/api.py#L54-L68

This means the non-list fields can be overwritten like the license in the .zenodo.json, but adding a related identifiers will remove the default related identifier (link to github release) and having creators in the .zenodo.json will skip adding github committers. So to have additional creators or related identifiers you need to track all the creators and release in the .zenodo.json your self.

**Comment by jspaaks** [comment]
permalink to @sverhoeven's snippet, for reference: https://github.com/inveniosoftware/invenio-github/blob/d0ca89f4692eeb7380e2e9c1c4b80c5dd5f028f3/invenio_github/utils.py#L52-L66

**Comment by jspaaks** [comment]
I've made a couple of pull requests to see if the ``.zenodo.json`` mechanism works:

- https://github.com/AA-ALERT/frbcat-web/pull/1
- https://github.com/AA-ALERT/frbcatdb/pull/7
- https://github.com/NLeSC/mcfly/pull/173

and updated the guide: 

- https://github.com/NLeSC/guide/pull/130
