### ISSUE TITLE
boatswain number of contributors incorrect

### ISSUE THREAD

**Issue by jspaaks** [research-software-directory/landing-page#8]

**Comment by Tommos0** [comment]
I see Berend + Jurriaan & the counter at 2; seems right?

**Comment by jspaaks** [comment]
Aha! yes, that's because I added Berend as a contributor this morning... I guess I was thrown off by contributors v contact person. SOmething to be aware of I guess but doesnt need code changes.

**Comment by jspaaks** [comment]
This needed to be reopened since it seems to have tripped up a couple more people:

- https://research-software.nl/software/ochre
- https://research-software.nl/software/3d-e-chem-knime-pharmacophore

It's more logical to add the set of contributors and the contact person, determine the unique set, then show the count as number of contributors at the top right of the frontend.

At the bottom of the page, show the unique set _minus_ the contact person as contributors, and show the contact person as the contact person at the bottom of the page.

**Comment by sverhoeven** [comment]
The admin and backend should validate that isContactPerson === true for one and only one contributor.

**Comment by sverhoeven** [comment]
See #98
