### ISSUE TITLE
Deployment behind single port and domain

### ISSUE THREAD

**Issue by sverhoeven** [research-software-directory/landing-page#86]
At the moment the production deployment uses sub domains for the different servers. In development localhost is used by all servers and each server is on a different port.

To make it easier to deploy it would be nice if all servers could be deployed behind a single domain and port. Paths should be used to separate the severs for example:
* https://somedomain/ , frontend server
* https://somedomain/api , backend server
* https://somedomain/admin , admin server
* https://somedomain/auth, auth server

**Comment by LourensVeen** [comment]
In Cerise I use nginx to glue things together like this, possibly useful config file: https://github.com/MD-Studio/cerise/blob/develop/conf/docker-nginx.conf

**Comment by Tommos0** [comment]
This is done with the current https://github.com/research-software-directory/stack configuration
