### ISSUE TITLE
Use ORCID?

### ISSUE THREAD

**Issue by tbkkr** [research-software-directory/landing-page#90]
Consider(ed) using ORCID or other author/researcher PIDs for contributor information? Might be relevant to at least consider adding that functionality in the future, so integration with journals, publishers, archives, online resumes etc is possible (perhaps for partners who would like to use the RSD) and auto-enrichting author names with hyperlinks, recent publications etc becomes possible.

see also the recent EU project FREYA: https://project-freya.eu/en/about/mission
and https://orcid.org/organizations/integrators

**Comment by tbkkr** [comment]
To think about enabling integration with ORCID (or other author PID systems) in the back, in the future. Front-end possible, but not really needed I guess.

Van: Jurriaan H. Spaaks <notifications@github.com>
Verzonden: woensdag 11 april 2018 12:22
Aan: research-software-directory/landing-page <landing-page@noreply.github.com>
CC: Tom Bakker <t.bakker@esciencecenter.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [research-software-directory/landing-page] Use ORCID? (#90)


For clarity, you are suggesting to put an ORCID next to the author's name on the human-readable text of the contributor section?

**Comment by jspaaks** [comment]
It is currently already possible to have the ORCID metadata as part of the CITATION.cff (e.g.https://github.com/NLeSC/ODEX-FAIRDataPoint/blob/a96125ba3c431a952c81ddfcffec9e5a970be46d/CITATION.cff#L9), but we're not displaying it on the frontpage (also not foreseen).
